// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Substitua pelos seus valores reais dentro das aspas
const SUPABASE_URL = "https://ufbddbhoubkxunpauorf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVmYmRkYmhvdWJreHVucGF1b3JmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzc4MTEwMzQsImV4cCI6MjA5MzM4NzAzNH0.qQHVYZ49WCK1xIkO8n_BdXYTVVvUOHjwHOuyr1FyrGg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
